name: credit_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #UI DESIGN
  cupertino_icons: 1.0.5
  font_awesome_flutter: 10.5.0
  dotted_border: 2.0.0+3
  carousel_slider: 4.2.1
  introduction_screen: 3.1.11
  scratcher: 2.3.0
  material_design_icons_flutter: 7.0.7296
  # convex_bottom_bar: 3.0.0
  convex_bottom_bar: 3.2.0
  #STATE MANAGEMENT
  get: 4.6.5

  #LOCAL 
  get_storage: 2.1.1

  #IMAGE
  image_picker: 1.0.1
  flutter_image_compress: 2.0.4
  image_cropper: 1.4.1

  #OTHERS
  intl: 0.18.1
  provider: 6.0.5
  flutter_svg: 2.0.7
  # pinput: 1.2.2
  pinput: 2.3.0
  page_view_indicators: 2.0.0
  date_format: 2.0.7
  # permission_handler: ^8.3.0
  permission_handler: 10.4.3
  dots_indicator: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf

